### ISSUE TITLE
右侧目录没有高亮及跟踪

### ISSUE THREAD

**Issue by isliangj** [lewis-geek/hexo-theme-Aath#30]
## 问题描述
在个人的 blog ，文章下滑过程中，右侧的目录没有高亮及跟踪，但在 Demo 中却是正常的。
## 问题图片
![2017-09-24 20 33 13](https://user-images.githubusercontent.com/24914221/30782622-1d303e90-a168-11e7-8a4c-9bded3b9a272.png)
## 浏览器类型及版本
Google Chrome 60.0.3112.113
## 操作系统及版本
macOS Sierra 10.12.6

**Comment by lewis-geek** [comment]
![image](https://user-images.githubusercontent.com/8927407/30949902-d95b3c5a-a3de-11e7-8bd5-5b468c70de06.png)

fixed #34
