### ISSUE TITLE
Error: no mixin named left-container

### ISSUE THREAD

**Issue by sanshishen** [lewis-geek/hexo-theme-Aath#65]
我是第一次使用hexo，之前也没有接触过sass/scss，当我按照readme.md操作之后，在执行“hexo g”命令时，报出了标题所示错误，请问是需要做什么额外的操作吗？

**Comment by sanshishen** [comment]
刚看到closed的issues里有相同的问题，但是我这边页面是没有样式的，或者说样式是错乱的

**Comment by lewis-geek** [comment]
若果你是在本地预览的话，请执行 `hexo server` 这个命令。

**Comment by lewis-geek** [comment]
fixed #67
