### ISSUE TITLE
search

### ISSUE THREAD

**Issue by zhaijiayu12345** [lewis-geek/hexo-theme-Aath#72]
可以使用站内搜索吗？而不是使用Google

**Comment by lewis-geek** [comment]
小的静态站点更适合用搜索引擎搜索，第三方的站内搜索工具注册流程复杂，功能还有限制 ~~我懒~~

如果提供一个百度搜索的方案可以满足你的需求吗？

**Comment by zhaijiayu12345** [comment]
那还不如用Google了呢（手动滑稽脸）

**Comment by lewis-geek** [comment]
暂不提供站内搜索功能

**Comment by cbtcbt** [comment]
> 如果提供一个百度搜索的方案可以满足你的需求吗？

请问百度搜索应该怎么配置呢，希望 @lewis-geek 能够帮忙回答或者提示一下，谢谢~

我刚刚用Hexo，在GitHub 和 coding.net上尝试了双部署，好让百度和谷歌都能索引到网站上的内容。主要是方便墙内使用。
