### ISSUE TITLE
project config error

### ISSUE THREAD

**Issue by ou-bing** [lewis-geek/hexo-theme-Aath#75]
在 project config 添加
`highlight:
  line_number: false`
生成时会报错：
`YAMLException: duplicated mapping key at line 80, column -62:
    highlight:`

**Comment by lewis-geek** [comment]
可能是你格式的问题
```yml
highlight: 
  line_number: false
```

**Comment by ou-bing** [comment]
我后来直接修改的 project 下的 _config.yml
