### ISSUE TITLE
how to enable comment

### ISSUE THREAD

**Issue by xiaoheigou** [lewis-geek/hexo-theme-Aath#78]
as title, how to add comment component to my blog,
Disqus_shortname: xiaoheigou
Livere_uid: MTAyMC8zNjY4Ny8xMzIyMg==

i have set the config,but cant see the comment on my site. please help

**Comment by lewis-geek** [comment]
`livere_uid` all lowercase, not `Livere_uid`

**Comment by lewis-geek** [comment]
你需要了解一下 [Disqus](https://help.disqus.com/) 或[Livere](https://livere.com/)，使用其中一个就行了，不需要两个都设置。

**Comment by xiaoheigou** [comment]
已经好了 哈哈 谢谢https://xiaoheigou.github.io/  群主是前端大佬。。
