### ISSUE TITLE
部分手机浏览器存在兼容问题。首页不显示文章浏览。

### ISSUE THREAD

**Issue by koibi2** [lewis-geek/hexo-theme-Aath#80]
我手里两个安卓手机的默认浏览器，首页都不显示文章浏览。
（内核版本：chrome30.0/chrome38.0）
![1](https://user-images.githubusercontent.com/34370367/44253222-6ff19280-a231-11e8-8513-3b693e2b9432.jpeg)
用chrome控制台调试了一下，好像是flex布局的问题。
（posts-list这个class不显示）
不知作者可否兼容下这些浏览器。感谢！

**Comment by lewis-geek** [comment]
这个主题主要面向开发人员使用的，开发人员的浏览器版本不会很老，所以用了很多较新的属性。你使用的两个浏览器实在太老了，Chrome 30 是 13 年发布的，不会考虑支持，抱歉!
