### ISSUE TITLE
文章页面，“目录”区域怎么隐藏大标题的序号？

### ISSUE THREAD

**Issue by koibi2** [lewis-geek/hexo-theme-Aath#83]
![baidushurufa_2018-10-14_2-15-4](https://user-images.githubusercontent.com/34370367/46908570-38644580-cf57-11e8-8265-22d68ebe7278.jpg)
个人习惯，写h2标题的时候会写序号。
然后本模板的目录，自动填充序号。重复了不好看。
源代码是这里：
`        
        <h1>目录</h1>
        <div class="content">
            <%- toc(page.content) %>
        </div>
`
翻了半天目录，不知道修改哪个文件能实现。
还望赐教，多谢！

**Comment by lewis-geek** [comment]
[layout/post.ejs#L45](https://github.com/lewis-geek/hexo-theme-Aath/blob/b785dfee245d4a69f6b2bce8bc9f4bade12bab91/layout/post.ejs#L45) 这一行添加参数 

[相关文档](https://hexo.io/zh-cn/docs/helpers#toc)
