### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by pierre94** [lewis-geek/hexo-theme-Aath#94]
Demo site is down

**Comment by lewis-geek** [comment]
Hi @pierre94 

If you want to check the demo you can check this link [hexo-theme-unit-test-site](https://lewis-geek.github.io/hexo-theme-unit-test/)

You can also clone the code from this repo [hexo-theme-unit-test](https://github.com/lewis-geek/hexo-theme-unit-test) and you can run this demo site in your local environment.

BTW, this theme no longer updated.

Cheers!
Yang
